# News Category Automation NLP

# Data Wrangling

## Import Modules

In [7]:
import pandas as pd
import numpy as np
import json
import os

## Load Data

In [10]:
file_name = "../data/raw/News_Category_Dataset_v3.json"
if os.path.exists(file_name):
    data = pd.read_json(file_name, lines=True, orient='columns')
else:
    print(f"File not found at {file_name}")
    print("Available files in current directory:")
    print(os.listdir('.'))

In [11]:
data.head()

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22

In [12]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 209527 entries, 0 to 209526
Data columns (total 6 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   link               209527 non-null  str
 1   headline           209527 non-null  str
 2   category           209527 non-null  str
 3   short_description  209527 non-null  str
 4   authors            209527 non-null  str
 5   date               209527 non-null  datetime64[us]
dtypes: datetime64[us](1), str(5)
memory usage: 9.6 MB

## Explore Data

In [13]:
#check for duplicates
duplicates = data.duplicated()
data[duplicates]

,link,headline,category,short_description,authors,date
67677,https://www.huffingtonpost.comhttp://www.mothe...,"On Facebook, Trump's Longtime Butler Calls For...",POLITICS,"Anthony Senecal, who worked as Donald Trump's ...",,2016-05-12
67923,https://www.huffingtonpost.comhttp://gizmodo.c...,Former Facebook Workers: We Routinely Suppress...,TECH,Facebook workers routinely suppressed news sto...,,2016-05-09
70239,https://www.huffingtonpost.comhttp://www.cnbc....,"On Equal Pay Day, The Gap Is Still Too Wide",WOMEN,Equal Pay Day falls on April 12 in 2016. It's ...,,2016-04-12
139830,https://www.huffingtonpost.comhttp://www.cnn.c...,The World's Most Dangerous Workout?,WELLNESS,"Is the ""sport of fitness"" the world's most dan...",,2014-02-10
144409,https://www.huffingtonpost.comhttp://www.upwor...,Some People Call It 'The Best Anti-Smoking Ad ...,WELLNESS,Almost all smokers know cigarettes are bad for...,,2013-12-22
145142,https://www.huffingtonpost.comhttp://www.weath...,10 Cities That Could Run Out Of Water - Weathe...,ENVIRONMENT,"Securing access to plentiful, renewable source...",,2013-12-15
178155,https://www.huffingtonpost.comhttp://www.busin...,Google Is Attacking Apple From The Inside Out ...,TECH,After years of hammering away at Apple's share...,,2013-01-01
187329,https://www.huffingtonpost.comhttp://www.nytim...,"Eating For Health, Not Weight",WELLNESS,Almost half of Americans are on a diet -- not ...,,2012-09-23
194596,https://www.huffingtonpost.comhttp://blogs.wsj...,Apple Removes Green EPEAT Electronics Certific...,TECH,Apple has pulled its products off the U.S. gov...,,2012-07-07
194598,https://www.huffingtonpost.comhttp://www.theda...,Microsoft's $6.2 Billion Writedown Shows It's ...,TECH,Fighting for online advertising dominance with...,,2012-07-07
207122,https://www.huffingtonpost.comhttp://d.repubbl...,Versace Atelier Worker Reflects On The Glory &...,STYLE & BEAUTY,"Twenty-four hours before the fashion show, Don...",,2012-02-23
207208,https://www.huffingtonpost.comhttp://d.repubbl...,Behind-The-Scenes Look At Prada's Workshop (VI...,STYLE & BEAUTY,Exclusive worldwide and for the first time in ...,,2012-02-22
207318,https://www.huffingtonpost.comhttp://d.repubbl...,Gucci's Frida Giannini Reveals Fashion Week Di...,STYLE & BEAUTY,Frida Giannini reveals in this worldwide exclu...,,2012-02-21

In [14]:
#drop duplicates
data.drop_duplicates(inplace=True)

#confirm no duplicates
data.duplicated().sum()

np.int64(0)

In [15]:
#count of each category
data['category'].value_counts()

category
POLITICS          35601
WELLNESS          17942
ENTERTAINMENT     17362
TRAVEL             9900
STYLE & BEAUTY     9811
PARENTING          8791
HEALTHY LIVING     6694
QUEER VOICES       6347
FOOD & DRINK       6340
BUSINESS           5992
COMEDY             5400
SPORTS             5077
BLACK VOICES       4583
HOME & LIVING      4320
PARENTS            3955
THE WORLDPOST      3664
WEDDINGS           3653
WOMEN              3571
CRIME              3562
IMPACT             3484
DIVORCE            3426
WORLD NEWS         3299
MEDIA              2944
WEIRD NEWS         2777
GREEN              2622
WORLDPOST          2579
RELIGION           2577
STYLE              2254
SCIENCE            2206
TECH               2100
TASTE              2096
MONEY              1756
ARTS               1509
ENVIRONMENT        1443
FIFTY              1401
GOOD NEWS          1398
U.S. NEWS          1377
ARTS & CULTURE     1339
COLLEGE            1144
LATINO VOICES      1130
CULTURE & ARTS     1074
EDUCATION          1014
Name: count, dtype: int64

There are a lot of categories and many of them are similar. It could be worth consolidating categories into broader terms.

Some other categories will have to be explored further to understand what they mean such as The Worldpost, Taste, Money, Fifty, and Good News

## Explore Categories

In [16]:
#The WorldPost
data[data['category'] == 'THE WORLDPOST'].head(10)

,link,headline,category,short_description,authors,date
22902,https://www.huffingtonpost.com/entry/north-kor...,It's Too Late To Stop North Korea As A Nuclear...,THE WORLDPOST,The window to roll back Pyongyang's weapons pr...,"Cui Lei, ContributorResearch fellow, China Ins...",2017-10-13
23954,https://www.huffingtonpost.com/entry/weekend-r...,Weekend Roundup: The Battle For Europe,THE WORLDPOST,Wary German voters and Catalan separatists are...,"Nathan Gardels, ContributorEditor-in-chief, Th...",2017-09-29
23979,https://www.huffingtonpost.com/entry/eu-france...,The Fate Of Europe Rests On The French-German ...,THE WORLDPOST,Macron and Merkel must figure out a common way...,"Sébastien Maillard, ContributorDirector, Jacqu...",2017-09-29
24046,https://www.huffingtonpost.com/entry/macron-me...,"After Merkel's Victory, Macron Sets Sights On ...",THE WORLDPOST,France’s transformation under Macron will push...,"Sylvie Goulard, ContributorFormer French defen...",2017-09-28
24460,https://www.huffingtonpost.com/entry/weekend-r...,Weekend Roundup: Trump's U.N. Speech Marks The...,THE WORLDPOST,We are leaving the postwar era that saw the U....,"Nathan Gardels, ContributorEditor-in-chief, Th...",2017-09-23
24477,https://www.huffingtonpost.com/entry/amal-cloo...,"Amal Clooney: 'Finally, We Have A Coordinated ...",THE WORLDPOST,"Thanks to a new international investigation, v...","Amal Clooney, ContributorLawyer, Activist and ...",2017-09-23
24544,https://www.huffingtonpost.com/entry/china-hol...,Why The China-Hollywood Relationship Is Compli...,THE WORLDPOST,"With China, Hollywood must navigate a constant...",Suzanne Gaber,2017-09-22
24654,https://www.huffingtonpost.com/entry/mike-meda...,Why The New Hollywood Will Never Live Up To Ol...,THE WORLDPOST,The industry has changed since the legendary t...,Rosa O'Hara,2017-09-21
24666,https://www.huffingtonpost.com/entry/trump-nat...,Why We Won’t See Trump-Like Nationalism In Ind...,THE WORLDPOST,"""America First"" is based in exclusivism, but I...","David T. Hill and Krishna Sen, Contributors",2017-09-21
24842,https://www.huffingtonpost.com/entry/islam-pop...,Islamist And Western Populism Have More In Com...,THE WORLDPOST,Reactive populism has become a decisive force ...,"Rainer Heufers, ContributorExecutive Director,...",2017-09-19

This seems like it is a combination of entertainment, world news/politics, and some tech. This can be combined with general news

In [17]:
# Taste Category
data[data['category'] == 'TASTE'].head(10)

,link,headline,category,short_description,authors,date
16173,https://www.huffingtonpost.com/entry/ice-water...,It's Weird That American Restaurants Serve Ice...,TASTE,But why do we even have ice in our drinks in t...,Todd Van Luling,2018-01-16
16242,https://www.huffingtonpost.com/entry/pineapple...,"Pineapple Casserole, The Southern Dish That's ...",TASTE,"It's got pineapple, cheddar and a whole lot of...",Kristen Aiken,2018-01-16
16516,https://www.huffingtonpost.com/entry/how-to-ge...,How To Actually Get A Bartender's Attention,TASTE,Plus other things they wish you knew.,Taylor Pittman,2018-01-11
16599,https://www.huffingtonpost.com/entry/diet-coke...,Diet Coke's Millennial-Inspired Makeover Leave...,TASTE,"It's not like a regular soda, it's a cool soda.",Abigail Williams,2018-01-10
16776,https://www.huffingtonpost.com/entry/sunions-t...,We Tested The New 'Tearless' Onions To See If ...,TASTE,"Put away your goggles, people.",Kristen Aiken,2018-01-08
16993,https://www.huffingtonpost.com/entry/in-n-out-...,In-N-Out Burger Now Serves Hot Cocoa And It's ...,TASTE,Some people are so excited.,Ron Dicker,2018-01-04
17007,https://www.huffingtonpost.com/entry/kfc-troll...,KFC Trolls Trump With Spoof Ronald McDonald Th...,TASTE,"""Mine is a box meal which is bigger and more p...",Lee Moran,2018-01-04
17138,https://www.huffingtonpost.com/entry/best-mock...,The Best Mocktails To Order At The Bar,TASTE,These aren't your lame old virgin daiquiris.,Kristen Aiken,2018-01-03
17144,https://www.huffingtonpost.com/entry/how-do-ai...,"How The Heck Do Air Fryers Work, Anyway?",TASTE,Make everyday Fry Day 🍟,Brittany Nims,2018-01-03
17271,https://www.huffingtonpost.com/entry/coffee-ca...,Coffee Cake To Cocktails: 20 Festive New Year'...,TASTE,There’s no better way to ring in the New Year ...,"Jennifer Segal, ContributorChef, Cookbook Auth...",2017-12-31

This can definitely be combined with the food & drink category

In [18]:
# Money
data[data['category'] == 'MONEY'].head(10)

,link,headline,category,short_description,authors,date
1796,https://www.huffpost.com/entry/holiday-shoppin...,Why You Should Get Your Holiday Shopping Done ...,MONEY,"Supply chain issues are out of your control, b...",Caroline Bologna,2021-10-21
3259,https://www.huffpost.com/entry/gamestop-stock-...,Investors Who Made Money Trading GameStop Have...,MONEY,"Those who recently flipped shares of GameStop,...",Casey Bond,2021-02-04
3335,https://www.huffpost.com/entry/tax-season-dela...,The IRS Delayed Tax Season. Here's How To Get ...,MONEY,Last-minute changes to tax laws in 2020 mean t...,Casey Bond,2021-01-22
4623,https://www.huffpost.com/entry/stimulus-check-...,Where's My Stimulus Check? How To Track Your C...,MONEY,"If your check was sent but you never got it, y...",Casey Bond,2020-06-16
4854,https://www.huffpost.com/entry/pay-taxes-coron...,Do You Have To Pay Taxes On Your Coronavirus S...,MONEY,Getting a payment won't mean a higher tax bill...,Casey Bond,2020-05-08
5182,https://www.huffpost.com/entry/bear-market-exp...,This Is What Happens When Stocks Enter A Bear ...,MONEY,"Experts say on average, bear markets have last...","Alex Viega, AP",2020-03-12
5183,https://www.huffpost.com/entry/coronavirus-cru...,Cruise Lines Are Paying Customers Not To Cance...,MONEY,"Would you risk your health ― and potentially, ...",Casey Bond,2020-03-12
5190,https://www.huffpost.com/entry/coronavirus-tim...,"Thanks To The Coronavirus, Now Is A Great Time...",MONEY,The only catch? There's much more demand than ...,Casey Bond,2020-03-10
5191,https://www.huffpost.com/entry/panic-buying-co...,The Psychology Behind Panic-Buying – And How T...,MONEY,"People are stockpiling – or ""panic-buying"" – t...",Natasha Hinde,2020-03-10
5239,https://www.huffpost.com/entry/buy-nothing-gro...,'Buy Nothing' Groups: Stop Spending Money And ...,MONEY,These Facebook groups prohibit exchanging mone...,Casey Bond,2020-02-28

This seems to be a lifestyle/shopping type of category rather than a business/financial focused

In [19]:
# Fifty
data[data['category'] == 'FIFTY'].head(10)

,link,headline,category,short_description,authors,date
43952,https://www.huffingtonpost.com/entry/love-face...,"Love, Facebook and Infidelity",FIFTY,,"Roz Warren, ContributorAuthor of OUR BODIES, O...",2017-02-05
47074,https://www.huffingtonpost.com/entry/boomers-w...,"Boomers Were Time's ""Man of the Year"" Fifty Ye...",FIFTY,,"Candy Leonard, ContributorSociologist, author ...",2017-01-02
47660,https://www.huffingtonpost.com/entry/be-gratef...,Be Grateful At The Holidays For Sprinkles Of H...,FIFTY,,"Honey Good, ContributorFounder of HoneyGood.com",2016-12-26
47711,https://www.huffingtonpost.com/entry/a-no-bull...,A No Bullsh-t Holiday Letter,FIFTY,,"Iris Ruth Pastor, ContributorSlice-of-life col...",2016-12-25
48303,https://www.huffingtonpost.com/entry/vocabular...,How Our Vocabulary Gives Away Our Age,FIFTY,We may look much younger than we really are. W...,"Delfín Carbonell, ContributorPh.D. in Philolog...",2016-12-18
48377,https://www.huffingtonpost.com/entry/living-ab...,The Truth About Retiring And Living Abroad Wit...,FIFTY,If you're hesitating making an international m...,"Kathleen Peddicord, ContributorPublisher, Live...",2016-12-17
48389,https://www.huffingtonpost.com/entry/joy-alzhe...,Bringing Joy To A Loved One With Alzheimer's,FIFTY,The concert would either bring Ed great joy or...,"Marie Marley, Contributoraward-winning author,...",2016-12-17
48966,https://www.huffingtonpost.com/entry/age-frien...,Age Friendliness on Our Minds,FIFTY,,"Marian L. Knapp, ContributorAuthor, columnist,...",2016-12-10
50141,https://www.huffingtonpost.com/entry/sexually-...,How To Become A Sexually Empowered Woman,FIFTY,There is a 'Divine Feminine Goddess' movement ...,"Pamela Madsen, ContributorSexuality and Relati...",2016-11-27
50142,https://www.huffingtonpost.com/entry/growing-u...,5 Things We Did As Children In The 1970s That ...,FIFTY,II grew up in the 70s and it was great. I had ...,"James Baxley, ContributorFreelance Writer, She...",2016-11-27

This is a category for the 50+ community. More focused on lifestyle than anything. Also seems to be a lot of missing descriptions here which we will have to tackle.

In [20]:
# Impact
data[data['category'] == 'IMPACT'].head(10)

,link,headline,category,short_description,authors,date
3834,https://www.huffpost.com/entry/why-you-shouldn...,Why You Shouldn't Recycle Receipts,IMPACT,CVS and other companies are shortening excessi...,Amanda Schupak,2020-10-30
3931,https://www.huffpost.com/entry/hummingbird-sav...,How One Of The World's Rarest Hummingbirds Is ...,IMPACT,The marvelous spatuletail hummingbird inspired...,Amanda Schupak,2020-10-13
3964,https://www.huffpost.com/entry/companies-clima...,Companies Are Making Major Climate Pledges. He...,IMPACT,How to decode corporate climate change targets...,Kyla Mandel,2020-10-07
4504,https://www.huffpost.com/entry/lisbon-airbnb-l...,Lisbon Says Airbnb Forced Out Locals. Here’s I...,IMPACT,The mayor of Portugal's capital city plans to ...,Laura Paddison,2020-07-07
4534,https://www.huffpost.com/entry/america-history...,Behind America’s Mutual Aid Boom Lies A Long H...,IMPACT,The tradition of mutual aid is as old as the c...,Amanda Schupak,2020-07-02
4536,https://www.huffpost.com/entry/grocery-list-en...,Is Your Grocery List Sustainable? We Asked Cli...,IMPACT,Here's what scientists refuse to buy when shop...,Kyla Mandel,2020-07-01
4548,https://www.huffpost.com/entry/four-day-workwe...,The Pandemic Could Finally Usher In The 4-Day ...,IMPACT,The U.S. has long resisted a more flexible wor...,Clio Chang,2020-06-29
4588,https://www.huffpost.com/entry/coronavirus-tra...,It’s Time For America To Get Serious About Fix...,IMPACT,Instead of spending billions to bail out airli...,Amy Crawford,2020-06-23
4928,https://www.huffpost.com/entry/construction-ma...,Construction Causes Major Pollution. Here's Ho...,IMPACT,The industry is four times more polluting than...,Zoë Schlanger,2020-04-25
4940,https://www.huffpost.com/entry/coronavirus-rem...,The Coronavirus Shows It's Time To Remake The ...,IMPACT,Cities across the U.S. and world are closing s...,Amy Crawford,2020-04-23

This seems to lean heavily toward environmental issues. We'll combine it with that

## Combine similar categories

I think we can combine these into 8 categories that should encapsule the broader topic of the news articles:

1.   News: Politics, The WorldPost, World News, Weird News, WorldPost,
Good News, U.S News, Crime
2. Arts & culture: Arts, Arts & Culture, Culture & Arts, Latino Voices, Religion, Queer Voices, Black Voices
3. Business: Business, Tech, Education
4. Sports
5. Entertainment: Media, Comedy, Entertainment
6. Health: Wellness, Food & Drink, Healthy Living, Taste
7. Science & Environment: Science, Environment, Green, Impact
8. Lifestyle: Fifty, College, Money, Divorce, Women, Weddings, Parents, Home & Living, Parenting, Style & Beauty, Travel, Style

In [21]:
# Combine categories
category_mapping = {
    'POLITICS': 'News',
    'THE WORLDPOST': 'News',
    'WORLD NEWS': 'News',
    'WEIRD NEWS': 'News',
    'WORLDPOST': 'News',
    'GOOD NEWS': 'News',
    'U.S. NEWS': 'News',
    'CRIME': 'News',
    'ARTS': 'Arts & Culture',
    'ARTS & CULTURE': 'Arts & Culture',
    'CULTURE & ARTS': 'Arts & Culture',
    'LATINO VOICES': 'Arts & Culture',
    'RELIGION': 'Arts & Culture',
    'QUEER VOICES': 'Arts & Culture',
    'BLACK VOICES': 'Arts & Culture',
    'BUSINESS': 'Business',
    'TECH': 'Business',
    'EDUCATION': 'Business',
    'SPORTS': 'Sports',
    'MEDIA': 'Entertainment',
    'COMEDY': 'Entertainment',
    'ENTERTAINMENT': 'Entertainment',
    'WELLNESS': 'Health',
    'FOOD & DRINK': 'Health',
    'HEALTHY LIVING': 'Health',
    'TASTE': 'Health',
    'SCIENCE': 'Science & Environment',
    'ENVIRONMENT': 'Science & Environment',
    'GREEN': 'Science & Environment',
    'IMPACT': 'Science & Environment',
    'FIFTY': 'Lifestyle',
    'COLLEGE': 'Lifestyle',
    'MONEY': 'Lifestyle',
    'DIVORCE': 'Lifestyle',
    'WOMEN': 'Lifestyle',
    'WEDDINGS': 'Lifestyle',
    'PARENTS': 'Lifestyle',
    'HOME & LIVING': 'Lifestyle',
    'PARENTING': 'Lifestyle',
    'STYLE & BEAUTY': 'Lifestyle',
    'TRAVEL': 'Lifestyle',
    'STYLE': 'Lifestyle'
}

data['category'] = data['category'].map(category_mapping)

# Display value counts for the new categories
display(data['category'].value_counts())

category
News                     54257
Lifestyle                53982
Health                   33072
Entertainment            25706
Arts & Culture           18559
Science & Environment     9755
Business                  9106
Sports                    5077
Name: count, dtype: int64

While some categories largely outweigh others, this will give us a better baseline for our model in the future.

## Review Missing data

In [22]:
# Review missing data
data.isna().sum()

link                 0
headline             0
category             0
short_description    0
authors              0
date                 0
dtype: int64

This shows no missing values but we saw missing values in the short descriptions previously. We'll check for empty strings instead.

In [23]:
#check if empty string in headlines & description
headline_missing = data[data['headline'] == '']
description_missing = data[data['short_description'] == '']
print(headline_missing.count())
print(description_missing.count())

link                 6
headline             6
category             6
short_description    6
authors              6
date                 6
dtype: int64
link                 19712
headline             19712
category             19712
short_description    19712
authors              19712
date                 19712
dtype: int64

There are only a few headlines missing which we could easily look up the headlines and add them. However about 10% of descriptions are empty so it may be worth it to scrape these pages for the headline and description

In [25]:
pip install bs4

Collecting bs4
  Downloading bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)
Collecting beautifulsoup4 (from bs4)
  Downloading beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4->bs4)
  Downloading soupsieve-2.8.4-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/timcarlon/Library/Python/3.11/lib/python/site-packages (from beautifulsoup4->bs4) (4.15.0)
Downloading bs4-0.0.2-py2.py3-none-any.whl (1.2 kB)
Downloading beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
Downloading soupsieve-2.8.4-py3-none-any.whl (37 kB)
Installing collected packages: soupsieve, beautifulsoup4, bs4
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [bs4]1/3 [beautifulsoup4]
Successfully installed beautifulsoup4-4.14.3 bs4-0.0.2 soupsieve-2.8.4

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [26]:
import requests
from bs4 import BeautifulSoup

#Scraping function
def scrape_missing_data(url, index):
  """Scrapes page for headine and description. Returns headline and description"""
  headline = ''
  description = ''
  try:
    response = requests.get(url)
    response.raise_for_status() #raise error for bad response
    soup = BeautifulSoup(response.content, 'html.parser')

    # Attempt to find the headline
    headline_tag = soup.find(['h1'])
    if headline_tag:
        headline = headline_tag.text.strip()

    # Attempt to find description-like content (can be adjusted based on typical website structure)
    description_tags = soup.find_all(['p', 'div'], class_=['dek', 'excerpt', 'description', 'summary']) # Common classes for descriptions
    if not description_tags: # If common classes not found, try to get text from p tags
        description_tags = soup.find_all('p')

    description_text = []
    for tag in description_tags:
      description_text.append(tag.text.strip())
    description = ' '.join(description_text)

  except HTTPError:
    pass
  except ConnectionError:
    pass
  except Timeout:
    pass
  except TooManyRedirects:
    pass
  except Exception as e:
    pass

  return headline, description

In [27]:
#combine headline & description missing
total_missing = pd.concat([headline_missing, description_missing])
total_missing.head()

,link,headline,category,short_description,authors,date
90944,https://www.huffingtonpost.com/entry/lincoln-2...,,News,,"Robert Moran, ContributorRobert Moran leads Br...",2015-08-22
95567,https://www.huffingtonpost.com/entry/post_9671...,,Arts & Culture,Let everyone not wrapped in tired and disprove...,"Matthew Fox, ContributorRadical theologian Mat...",2015-06-30
103675,https://www.huffingtonpost.com/entry/us-and-eu...,,News,,"Natasha Srdoc, ContributorAuthor, Economist, C...",2015-03-29
109100,https://www.huffingtonpost.com/entry/disney-ce...,,Business,,"Gary Snyder, ContributorWriter and Media Strat...",2015-01-25
110153,https://www.huffingtonpost.com/entry/beverly-h...,,Entertainment,,"Gary Snyder, ContributorWriter and Media Strat...",2015-01-13

In [33]:
pip install aiohttp

Collecting aiohttp
  Downloading aiohttp-3.14.0-cp311-cp311-macosx_10_9_x86_64.whl.metadata (8.3 kB)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp)
  Downloading aiohappyeyeballs-2.6.2-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp)
  Downloading aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Collecting attrs>=17.3.0 (from aiohttp)
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting frozenlist>=1.1.1 (from aiohttp)
  Downloading frozenlist-1.8.0-cp311-cp311-macosx_10_9_x86_64.whl.metadata (20 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp)
  Downloading multidict-6.7.1-cp311-cp311-macosx_10_9_x86_64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp)
  Downloading propcache-0.5.2-cp311-cp311-macosx_10_9_x86_64.whl.metadata (16 kB)
Requirement already satisfied: typing_extensions>=4.4 in /Users/timcarlon/Library/Python/3.11/lib/python/site-packages (from aiohttp) (4.15.0)
Collecting yarl<2.0,>=1.17.0 (from aiohttp)
  Downloading yarl-1.24.2-cp311-cp311-macosx_10_9_x86_64.whl.metadata (94 kB)
Requirement already satisfied: idna>=2.0 in /Users/timcarlon/Library/Python/3.11/lib/python/site-packages (from yarl<2.0,>=1.17.0->aiohttp) (3.11)
Downloading aiohttp-3.14.0-cp311-cp311-macosx_10_9_x86_64.whl (513 kB)
Downloading multidict-6.7.1-cp311-cp311-macosx_10_9_x86_64.whl (44 kB)
Downloading yarl-1.24.2-cp311-cp311-macosx_10_9_x86_64.whl (91 kB)
Downloading aiohappyeyeballs-2.6.2-py3-none-any.whl (15 kB)
Downloading aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
Downloading frozenlist-1.8.0-cp311-cp311-macosx_10_9_x86_64.whl (50 kB)
Downloading propcache-0.5.2-cp311-cp311-macosx_10_9_x86_64.whl (52 kB)
Installing collected packages: propcache, multidict, frozenlist, attrs, aiohappyeyeballs, yarl, aiosignal, aiohttp
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8/8 [aiohttp]m7/8 [aiohttp]
Successfully installed aiohappyeyeballs-2.6.2 aiohttp-3.14.0 aiosignal-1.4.0 attrs-26.1.0 frozenlist-1.8.0 multidict-6.7.1 propcache-0.5.2 yarl-1.24.2

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [34]:
import asyncio
import aiohttp
from bs4 import BeautifulSoup

# Async scraping function
async def fetch_and_parse(session, idx, url):
    headline = ''
    description = ''
    try:
        async with session.get(url, timeout=aiohttp.ClientTimeout(total=15)) as resp:
            resp.raise_for_status()
            text = await resp.text()
        soup = BeautifulSoup(text, 'html.parser')
        h = soup.find('h1')
        if h:
            headline = h.get_text(strip=True)
        description_tags = soup.find_all(['p', 'div'], class_=['dek', 'excerpt', 'description', 'summary'])
        if not description_tags:
            description_tags = soup.find_all('p')
        description = ' '.join([t.get_text(strip=True) for t in description_tags])
    except Exception:
        pass
    return idx, headline, description

async def run_async_scrape():
    max_workers = 20
    connector = aiohttp.TCPConnector(limit=max_workers, ssl=False)
    headers = {'User-Agent': 'Mozilla/5.0 (compatible; NewsScraper/1.0)', 'Accept-Encoding': 'gzip, deflate'}
    async with aiohttp.ClientSession(headers=headers, connector=connector) as session:
        tasks = [fetch_and_parse(session, idx, row['link']) for idx, row in total_missing.iterrows()]
        for coro in asyncio.as_completed(tasks):
            idx, headline, description = await coro
            if description:
                total_missing.loc[idx, 'short_description'] = description
            if headline:
                total_missing.loc[idx, 'headline'] = headline

await run_async_scrape()

total_missing.head()

Exception ignored in: <function tqdm.__del__ at 0x10d958b80>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tqdm/notebook.py", line 277, in close
    self.disp(bar_style='danger', check_delay=False)
    ^^^^^^^^^
AttributeError: 'tqdm_notebook' object has no attribute 'disp'

,link,headline,category,short_description,authors,date
90944,https://www.huffingtonpost.com/entry/lincoln-2...,Lincoln 2.0?,News,Could we ever vote for an Abraham Lincoln 2.0 ...,"Robert Moran, ContributorRobert Moran leads Br...",2015-08-22
95567,https://www.huffingtonpost.com/entry/post_9671...,,Arts & Culture,Let everyone not wrapped in tired and disprove...,"Matthew Fox, ContributorRadical theologian Mat...",2015-06-30
103675,https://www.huffingtonpost.com/entry/us-and-eu...,HUFFPOST,News,Do you have info to share with HuffPost report...,"Natasha Srdoc, ContributorAuthor, Economist, C...",2015-03-29
109100,https://www.huffingtonpost.com/entry/disney-ce...,HUFFPOST,Business,Do you have info to share with HuffPost report...,"Gary Snyder, ContributorWriter and Media Strat...",2015-01-25
110153,https://www.huffingtonpost.com/entry/beverly-h...,HUFFPOST,Entertainment,Do you have info to share with HuffPost report...,"Gary Snyder, ContributorWriter and Media Strat...",2015-01-13

In [35]:
# Check number of missing
total_missing[total_missing['short_description'] == ''].count()

link                 18171
headline             18171
category             18171
short_description    18171
authors              18171
date                 18171
dtype: int64

In [36]:
#view rows with headline/description scraped
pd.set_option('display.max_colwidth', None)
total_missing.head(25)

,link,headline,category,short_description,authors,date
90944,https://www.huffingtonpost.com/entry/lincoln-20_b_8023742.html,Lincoln 2.0?,News,Could we ever vote for an Abraham Lincoln 2.0 - an artificial intelligence built to replicate the decision making style of one of our most accomplished Presidents?,"Robert Moran, ContributorRobert Moran leads Brunswick Insight, and writes and speaks on...",2015-08-22
95567,https://www.huffingtonpost.com/entry/post_9671_b_7683632.html,,Arts & Culture,"Let everyone not wrapped in tired and disproven doctrines about sex rid themselves of anti-scientific dogmas and be free. The law of grace, not of fear, can now blow freely.","Matthew Fox, ContributorRadical theologian Matthew Fox is the author of more than 30 b...",2015-06-30
103675,https://www.huffingtonpost.com/entry/us-and-europes-economic-a_b_6962262.html,HUFFPOST,News,"Do you have info to share with HuffPost reporters? Here’s how. By entering your email and clicking Sign Up, you're agreeing to let us send you customized marketing messages about us and our advertising partners. You are also agreeing to our Terms of Service and Privacy Policy. Do you have info to share with HuffPost reporters? Here’s how.","Natasha Srdoc, ContributorAuthor, Economist, Co-Founder, Adriatic Institute and Internat...",2015-03-29
109100,https://www.huffingtonpost.com/entry/disney-ceo-iger-readies-m_b_6520290.html,HUFFPOST,Business,"Do you have info to share with HuffPost reporters? Here’s how. By entering your email and clicking Sign Up, you're agreeing to let us send you customized marketing messages about us and our advertising partners. You are also agreeing to our Terms of Service and Privacy Policy. Do you have info to share with HuffPost reporters? Here’s how.","Gary Snyder, ContributorWriter and Media Strategist",2015-01-25
110153,https://www.huffingtonpost.com/entry/beverly-hills-hotel-caugh_b_6414708.html,HUFFPOST,Entertainment,"Do you have info to share with HuffPost reporters? Here’s how. By entering your email and clicking Sign Up, you're agreeing to let us send you customized marketing messages about us and our advertising partners. You are also agreeing to our Terms of Service and Privacy Policy. Do you have info to share with HuffPost reporters? Here’s how.","Gary Snyder, ContributorWriter and Media Strategist",2015-01-13
122145,https://www.huffingtonpost.com/entry/beverly-hills-hotel-boyco_b_5711931.html,HUFFPOST,Arts & Culture,"Do you have info to share with HuffPost reporters? Here’s how. By entering your email and clicking Sign Up, you're agreeing to let us send you customized marketing messages about us and our advertising partners. You are also agreeing to our Terms of Service and Privacy Policy. Do you have info to share with HuffPost reporters? Here’s how.","Gary Snyder, ContributorWriter and Media Strategist",2014-08-28
20773,https://www.huffingtonpost.com/entry/the-big-blue-wave_us_5a050838e4b0ee8ec3694054,The Big Blue Wave,Entertainment,The Big Blue Wave,"Shan Wells, ContributorSciency sun venerator + cartoons",2017-11-10
21523,https://www.huffingtonpost.com/entry/inside-rukban-camp-one-of-syrias-most-desperate-settlements_us_59f87fd8e4b0aec1467ace64,"Inside Rukban Camp, One Of Syria’s Most Desperate Settlements",News,"Inside Rukban Camp, One Of Syria’s Most Desperate Settlements","Yasser Allawi, Syria Deeply",2017-10-31
22793,https://www.huffingtonpost.com/entry/syrian-refugees-return-from-lebanon-only-to-flee-war-yet-again_us_59e263d6e4b03a7be580fff6,Syrian Refugees Return From Lebanon Only To Flee War Yet Again,News,Syrian Refugees Return From Lebanon Only To Flee War Yet Again,"Abby Sewell, Refugees Deeply",2017-10-14
32223,https://www.huffingtonpost.com/entry/your-guide-to-the-best-bbq-in-st-louis_us_594806e8e4b0cddbb0088011,Your Guide To The Best BBQ In St. Louis According to Zagat,Health,"Your Guide To The Best BBQ In St. Louis According to Zagat Tourist or local, this place has great BBQ",,2017-06-19
34488,https://www.huffingtonpost.com/entry/the-bechdel-test_us_5925be6be4b0dfb1ca3a106a,The Bechdel Test,Entertainment,The Bechdel Test,"Hilary Fitzgerald Campbell, ContributorHilary's cartoons have appeared in The New Yorker and other fu...",2017-05-24
35584,https://www.huffingtonpost.com/entry/how-to-add-some-activism-to-your-mothers-day-traditions_us_59147334e4b030d4f1f059d0,How To Add Some Activism To Your Mother's Day Traditions,Lifestyle,Brought to you by the Women's March.,Jenavieve Hatch,2017-05-11
35692,https://www.huffingtonpost.com/entry/how-to-add-some-activism-to-your-mothers-day-traditions_us_59131c5de4b0a58297e13ded,How To Add Some Activism To Your Mother's Day Traditions,Lifestyle,Brought to you by the Women's March.,Jenavieve Hatch,2017-05-10
40313,https://www.huffingtonpost.com/entry/fired-us-attorney-preet-bharara-said-to-have-been-investigating-hhs-secretary-tom-price_us_58cc2b1ee4b0be71dcf4a17b,Fired U.S. Attorney Preet Bharara Said to Have Been Investigating HHS Secretary Tom Price,News,REPORT: Preet Was Investigating Trump's Health Secretary At Time Of Firing,"Robert Faturechi, ProPublica",2017-03-17
43295,https://www.huffingtonpost.com/entry/love-needs-to-be-remember_b_14696322.html,"Love Needs To Be Remembered, Restored and Renewed",Health,"Love Needs To Be Remembered, Restored and Renewed","Ed and Deb Shapiro, ContributorMindfulness, Meditation, Yoga experts; Bestselling Authors: YO...",2017-02-12
43296,https://www.huffingtonpost.com/entry/a-new-american-strategy-i_b_14698080.html,A New American Strategy in the Middle East,News,A New American Strategy in the Middle East,"Raghida Dergham, ContributorColumnist and Senior Diplomatic Correspondent, Al Hayat",2017-02-12
43297,https://www.huffingtonpost.com/entry/a-price-on-carbon-is-neit_b_14703122.html,A Price On Carbon Is Neither Liberal Nor Conservative. It's Just Practical,Science & Environment,A Price On Carbon Is Neither Liberal Nor Conservative. It's Just Practical,"Steve Zwick, ContributorWriter, Reporter, Pragmatic Tree-Hugger",2017-02-12
43298,https://www.huffingtonpost.com/entry/geoff-cowan-former-head-o_b_14693992.html,"Geoff Cowan, Former Head of Voice of America, Stresses the Need for a Strong Press in the Trump Age",News,"Geoff Cowan, Former Head of Voice of America, Stresses the Need for a Strong Press in the Trump Age","Robert Scheer, ContributorEditor, Truthdig.com; Author, 'They Know Everything About You'",2017-02-12
43299,https://www.huffingtonpost.com/entry/donald-trump-only-knows-h_b_14689290.html,Donald Trump Only Knows How to Do One Thing -- And It Isn't Being President,News,Donald Trump Only Knows How to Do One Thing -- And It Isn't Being President,"Nell Minow, ContributorMovie critic, corporate governance analyst",2017-02-12
43300,https://www.huffingtonpost.com/entry/islamic-republic-of-irans_b_14697016.html,Islamic Republic of Iran's Lobbyists and Spies Are in Our Midst?,News,Islamic Republic of Iran's Lobbyists and Spies Are in Our Midst?,"Dr. Majid Rafizadeh, ContributorPresident of the International American Council",2017-02-12
43301,https://www.huffingtonpost.com/entry/price-wrong-and-lower-you_b_14697472.html,Price Wrong and Lower Your Profits,Business,Price Wrong and Lower Your Profits,"Ira Kalb, ContributorAssistant Professor of Clinical Marketing, Marshall School of ...",2017-02-12
43302,https://www.huffingtonpost.com/entry/how-to-make-gyoza-japanes_b_14700656.html,"How to Make Gyoza, Japanese Fried Dumplings Recipe",Health,"How to Make Gyoza, Japanese Fried Dumplings Recipe","Vincenzo Prosperi, ContributorFood Blogger at www.vincenzosplate.com, Youtube Cooking show",2017-02-12
43303,https://www.huffingtonpost.com/entry/how-john-cenas-wrestleman_b_14701174.html,How John Cena's Wrestlemania 33 Opponent Is Chosen... | WrestleSketch #12,Sports,How John Cena's Wrestlemania 33 Opponent Is Chosen... | WrestleSketch #12,"Oli Davis, ContributorOli Davis is the guy all over WrestleTalk's YouTube channel an...",2017-02-12
43304,https://www.huffingtonpost.com/entry/goldbergs-wwe-return-succ_b_14701044.html,Goldberg's WWE Return Success Reason Revealed! Backstage Heat Between TNA & ROH! | WrestleTalk News,Sports,Goldberg's WWE Return Success Reason Revealed! Backstage Heat Between TNA & ROH! | WrestleTalk News,"Oli Davis, ContributorOli Davis is the guy all over WrestleTalk's YouTube channel an...",2017-02-12
43305,https://www.huffingtonpost.com/entry/oscarnomics-2017-the-bran_b_14711164.html,Oscarnomics 2017: The Brand Value of Awards,Business,Oscarnomics 2017: The Brand Value of Awards,"Ira Kalb, ContributorAssistant Professor of Clinical Marketing, Marshall School of ...",2017-02-12

In [37]:
#removing urls that redirected to home page
total_missing = total_missing[total_missing['short_description'] != "For two decades, HuffPost has been fearless, unflinching, and relentless in pursuit of the truth. Support our mission to keep us around for the next 20 — we can't do this without you. We remain committed to providing you with the unflinching, fact-based journalism everyone deserves.Thank you again for your support along the way. We’re truly grateful for readers like you! Your initial support helped get us here and bolstered our newsroom, which kept us strong during uncertain times. Now as we continue, we need your help more than ever. We hope you will join us once again. We remain committed to providing you with the unflinching, fact-based journalism everyone deserves.Thank you again for your support along the way. We’re truly grateful for readers like you! Your initial support helped get us here and bolstered our newsroom, which kept us strong during uncertain times. Now as we continue, we need your help more than ever. We hope you will join us once again. Already contributed? Log in to hide these messages. Do you have info to share with HuffPost reporters? Here’s how. By entering your email and clicking Sign Up, you're agreeing to let us send you customized marketing messages about us and our advertising partners. You are also agreeing to our Terms of Service and Privacy Policy. Do you have info to share with HuffPost reporters? Here’s how."]

In [38]:
total_missing.head(25)

,link,headline,category,short_description,authors,date
90944,https://www.huffingtonpost.com/entry/lincoln-20_b_8023742.html,Lincoln 2.0?,News,Could we ever vote for an Abraham Lincoln 2.0 - an artificial intelligence built to replicate the decision making style of one of our most accomplished Presidents?,"Robert Moran, ContributorRobert Moran leads Brunswick Insight, and writes and speaks on...",2015-08-22
95567,https://www.huffingtonpost.com/entry/post_9671_b_7683632.html,,Arts & Culture,"Let everyone not wrapped in tired and disproven doctrines about sex rid themselves of anti-scientific dogmas and be free. The law of grace, not of fear, can now blow freely.","Matthew Fox, ContributorRadical theologian Matthew Fox is the author of more than 30 b...",2015-06-30
103675,https://www.huffingtonpost.com/entry/us-and-europes-economic-a_b_6962262.html,HUFFPOST,News,"Do you have info to share with HuffPost reporters? Here’s how. By entering your email and clicking Sign Up, you're agreeing to let us send you customized marketing messages about us and our advertising partners. You are also agreeing to our Terms of Service and Privacy Policy. Do you have info to share with HuffPost reporters? Here’s how.","Natasha Srdoc, ContributorAuthor, Economist, Co-Founder, Adriatic Institute and Internat...",2015-03-29
109100,https://www.huffingtonpost.com/entry/disney-ceo-iger-readies-m_b_6520290.html,HUFFPOST,Business,"Do you have info to share with HuffPost reporters? Here’s how. By entering your email and clicking Sign Up, you're agreeing to let us send you customized marketing messages about us and our advertising partners. You are also agreeing to our Terms of Service and Privacy Policy. Do you have info to share with HuffPost reporters? Here’s how.","Gary Snyder, ContributorWriter and Media Strategist",2015-01-25
110153,https://www.huffingtonpost.com/entry/beverly-hills-hotel-caugh_b_6414708.html,HUFFPOST,Entertainment,"Do you have info to share with HuffPost reporters? Here’s how. By entering your email and clicking Sign Up, you're agreeing to let us send you customized marketing messages about us and our advertising partners. You are also agreeing to our Terms of Service and Privacy Policy. Do you have info to share with HuffPost reporters? Here’s how.","Gary Snyder, ContributorWriter and Media Strategist",2015-01-13
122145,https://www.huffingtonpost.com/entry/beverly-hills-hotel-boyco_b_5711931.html,HUFFPOST,Arts & Culture,"Do you have info to share with HuffPost reporters? Here’s how. By entering your email and clicking Sign Up, you're agreeing to let us send you customized marketing messages about us and our advertising partners. You are also agreeing to our Terms of Service and Privacy Policy. Do you have info to share with HuffPost reporters? Here’s how.","Gary Snyder, ContributorWriter and Media Strategist",2014-08-28
20773,https://www.huffingtonpost.com/entry/the-big-blue-wave_us_5a050838e4b0ee8ec3694054,The Big Blue Wave,Entertainment,The Big Blue Wave,"Shan Wells, ContributorSciency sun venerator + cartoons",2017-11-10
21523,https://www.huffingtonpost.com/entry/inside-rukban-camp-one-of-syrias-most-desperate-settlements_us_59f87fd8e4b0aec1467ace64,"Inside Rukban Camp, One Of Syria’s Most Desperate Settlements",News,"Inside Rukban Camp, One Of Syria’s Most Desperate Settlements","Yasser Allawi, Syria Deeply",2017-10-31
22793,https://www.huffingtonpost.com/entry/syrian-refugees-return-from-lebanon-only-to-flee-war-yet-again_us_59e263d6e4b03a7be580fff6,Syrian Refugees Return From Lebanon Only To Flee War Yet Again,News,Syrian Refugees Return From Lebanon Only To Flee War Yet Again,"Abby Sewell, Refugees Deeply",2017-10-14
32223,https://www.huffingtonpost.com/entry/your-guide-to-the-best-bbq-in-st-louis_us_594806e8e4b0cddbb0088011,Your Guide To The Best BBQ In St. Louis According to Zagat,Health,"Your Guide To The Best BBQ In St. Louis According to Zagat Tourist or local, this place has great BBQ",,2017-06-19
34488,https://www.huffingtonpost.com/entry/the-bechdel-test_us_5925be6be4b0dfb1ca3a106a,The Bechdel Test,Entertainment,The Bechdel Test,"Hilary Fitzgerald Campbell, ContributorHilary's cartoons have appeared in The New Yorker and other fu...",2017-05-24
35584,https://www.huffingtonpost.com/entry/how-to-add-some-activism-to-your-mothers-day-traditions_us_59147334e4b030d4f1f059d0,How To Add Some Activism To Your Mother's Day Traditions,Lifestyle,Brought to you by the Women's March.,Jenavieve Hatch,2017-05-11
35692,https://www.huffingtonpost.com/entry/how-to-add-some-activism-to-your-mothers-day-traditions_us_59131c5de4b0a58297e13ded,How To Add Some Activism To Your Mother's Day Traditions,Lifestyle,Brought to you by the Women's March.,Jenavieve Hatch,2017-05-10
40313,https://www.huffingtonpost.com/entry/fired-us-attorney-preet-bharara-said-to-have-been-investigating-hhs-secretary-tom-price_us_58cc2b1ee4b0be71dcf4a17b,Fired U.S. Attorney Preet Bharara Said to Have Been Investigating HHS Secretary Tom Price,News,REPORT: Preet Was Investigating Trump's Health Secretary At Time Of Firing,"Robert Faturechi, ProPublica",2017-03-17
43295,https://www.huffingtonpost.com/entry/love-needs-to-be-remember_b_14696322.html,"Love Needs To Be Remembered, Restored and Renewed",Health,"Love Needs To Be Remembered, Restored and Renewed","Ed and Deb Shapiro, ContributorMindfulness, Meditation, Yoga experts; Bestselling Authors: YO...",2017-02-12
43296,https://www.huffingtonpost.com/entry/a-new-american-strategy-i_b_14698080.html,A New American Strategy in the Middle East,News,A New American Strategy in the Middle East,"Raghida Dergham, ContributorColumnist and Senior Diplomatic Correspondent, Al Hayat",2017-02-12
43297,https://www.huffingtonpost.com/entry/a-price-on-carbon-is-neit_b_14703122.html,A Price On Carbon Is Neither Liberal Nor Conservative. It's Just Practical,Science & Environment,A Price On Carbon Is Neither Liberal Nor Conservative. It's Just Practical,"Steve Zwick, ContributorWriter, Reporter, Pragmatic Tree-Hugger",2017-02-12
43298,https://www.huffingtonpost.com/entry/geoff-cowan-former-head-o_b_14693992.html,"Geoff Cowan, Former Head of Voice of America, Stresses the Need for a Strong Press in the Trump Age",News,"Geoff Cowan, Former Head of Voice of America, Stresses the Need for a Strong Press in the Trump Age","Robert Scheer, ContributorEditor, Truthdig.com; Author, 'They Know Everything About You'",2017-02-12
43299,https://www.huffingtonpost.com/entry/donald-trump-only-knows-h_b_14689290.html,Donald Trump Only Knows How to Do One Thing -- And It Isn't Being President,News,Donald Trump Only Knows How to Do One Thing -- And It Isn't Being President,"Nell Minow, ContributorMovie critic, corporate governance analyst",2017-02-12
43300,https://www.huffingtonpost.com/entry/islamic-republic-of-irans_b_14697016.html,Islamic Republic of Iran's Lobbyists and Spies Are in Our Midst?,News,Islamic Republic of Iran's Lobbyists and Spies Are in Our Midst?,"Dr. Majid Rafizadeh, ContributorPresident of the International American Council",2017-02-12
43301,https://www.huffingtonpost.com/entry/price-wrong-and-lower-you_b_14697472.html,Price Wrong and Lower Your Profits,Business,Price Wrong and Lower Your Profits,"Ira Kalb, ContributorAssistant Professor of Clinical Marketing, Marshall School of ...",2017-02-12
43302,https://www.huffingtonpost.com/entry/how-to-make-gyoza-japanes_b_14700656.html,"How to Make Gyoza, Japanese Fried Dumplings Recipe",Health,"How to Make Gyoza, Japanese Fried Dumplings Recipe","Vincenzo Prosperi, ContributorFood Blogger at www.vincenzosplate.com, Youtube Cooking show",2017-02-12
43303,https://www.huffingtonpost.com/entry/how-john-cenas-wrestleman_b_14701174.html,How John Cena's Wrestlemania 33 Opponent Is Chosen... | WrestleSketch #12,Sports,How John Cena's Wrestlemania 33 Opponent Is Chosen... | WrestleSketch #12,"Oli Davis, ContributorOli Davis is the guy all over WrestleTalk's YouTube channel an...",2017-02-12
43304,https://www.huffingtonpost.com/entry/goldbergs-wwe-return-succ_b_14701044.html,Goldberg's WWE Return Success Reason Revealed! Backstage Heat Between TNA & ROH! | WrestleTalk News,Sports,Goldberg's WWE Return Success Reason Revealed! Backstage Heat Between TNA & ROH! | WrestleTalk News,"Oli Davis, ContributorOli Davis is the guy all over WrestleTalk's YouTube channel an...",2017-02-12
43305,https://www.huffingtonpost.com/entry/oscarnomics-2017-the-bran_b_14711164.html,Oscarnomics 2017: The Brand Value of Awards,Business,Oscarnomics 2017: The Brand Value of Awards,"Ira Kalb, ContributorAssistant Professor of Clinical Marketing, Marshall School of ...",2017-02-12

In [39]:
#check where description and headline are exact match
total_missing[total_missing['short_description'] == total_missing['headline']].count()

link                 1271
headline             1271
category             1271
short_description    1271
authors              1271
date                 1271
dtype: int64

In [40]:
# drop where exact match
total_missing = total_missing[total_missing['short_description'] != total_missing['headline']]
total_missing.head(25)

,link,headline,category,short_description,authors,date
90944,https://www.huffingtonpost.com/entry/lincoln-20_b_8023742.html,Lincoln 2.0?,News,Could we ever vote for an Abraham Lincoln 2.0 - an artificial intelligence built to replicate the decision making style of one of our most accomplished Presidents?,"Robert Moran, ContributorRobert Moran leads Brunswick Insight, and writes and speaks on...",2015-08-22
95567,https://www.huffingtonpost.com/entry/post_9671_b_7683632.html,,Arts & Culture,"Let everyone not wrapped in tired and disproven doctrines about sex rid themselves of anti-scientific dogmas and be free. The law of grace, not of fear, can now blow freely.","Matthew Fox, ContributorRadical theologian Matthew Fox is the author of more than 30 b...",2015-06-30
103675,https://www.huffingtonpost.com/entry/us-and-europes-economic-a_b_6962262.html,HUFFPOST,News,"Do you have info to share with HuffPost reporters? Here’s how. By entering your email and clicking Sign Up, you're agreeing to let us send you customized marketing messages about us and our advertising partners. You are also agreeing to our Terms of Service and Privacy Policy. Do you have info to share with HuffPost reporters? Here’s how.","Natasha Srdoc, ContributorAuthor, Economist, Co-Founder, Adriatic Institute and Internat...",2015-03-29
109100,https://www.huffingtonpost.com/entry/disney-ceo-iger-readies-m_b_6520290.html,HUFFPOST,Business,"Do you have info to share with HuffPost reporters? Here’s how. By entering your email and clicking Sign Up, you're agreeing to let us send you customized marketing messages about us and our advertising partners. You are also agreeing to our Terms of Service and Privacy Policy. Do you have info to share with HuffPost reporters? Here’s how.","Gary Snyder, ContributorWriter and Media Strategist",2015-01-25
110153,https://www.huffingtonpost.com/entry/beverly-hills-hotel-caugh_b_6414708.html,HUFFPOST,Entertainment,"Do you have info to share with HuffPost reporters? Here’s how. By entering your email and clicking Sign Up, you're agreeing to let us send you customized marketing messages about us and our advertising partners. You are also agreeing to our Terms of Service and Privacy Policy. Do you have info to share with HuffPost reporters? Here’s how.","Gary Snyder, ContributorWriter and Media Strategist",2015-01-13
122145,https://www.huffingtonpost.com/entry/beverly-hills-hotel-boyco_b_5711931.html,HUFFPOST,Arts & Culture,"Do you have info to share with HuffPost reporters? Here’s how. By entering your email and clicking Sign Up, you're agreeing to let us send you customized marketing messages about us and our advertising partners. You are also agreeing to our Terms of Service and Privacy Policy. Do you have info to share with HuffPost reporters? Here’s how.","Gary Snyder, ContributorWriter and Media Strategist",2014-08-28
32223,https://www.huffingtonpost.com/entry/your-guide-to-the-best-bbq-in-st-louis_us_594806e8e4b0cddbb0088011,Your Guide To The Best BBQ In St. Louis According to Zagat,Health,"Your Guide To The Best BBQ In St. Louis According to Zagat Tourist or local, this place has great BBQ",,2017-06-19
35584,https://www.huffingtonpost.com/entry/how-to-add-some-activism-to-your-mothers-day-traditions_us_59147334e4b030d4f1f059d0,How To Add Some Activism To Your Mother's Day Traditions,Lifestyle,Brought to you by the Women's March.,Jenavieve Hatch,2017-05-11
35692,https://www.huffingtonpost.com/entry/how-to-add-some-activism-to-your-mothers-day-traditions_us_59131c5de4b0a58297e13ded,How To Add Some Activism To Your Mother's Day Traditions,Lifestyle,Brought to you by the Women's March.,Jenavieve Hatch,2017-05-10
40313,https://www.huffingtonpost.com/entry/fired-us-attorney-preet-bharara-said-to-have-been-investigating-hhs-secretary-tom-price_us_58cc2b1ee4b0be71dcf4a17b,Fired U.S. Attorney Preet Bharara Said to Have Been Investigating HHS Secretary Tom Price,News,REPORT: Preet Was Investigating Trump's Health Secretary At Time Of Firing,"Robert Faturechi, ProPublica",2017-03-17
43951,https://www.huffingtonpost.com/entry/evolution-weekend-now-mor_b_14629804.html,Evolution Weekend: Now More Than Ever!,Arts & Culture,Evolution Weekend: Now More Than Ever!,"Michael Zimmerman, Ph.D., ContributorFounder, The Clergy Letter Project",2017-02-05
44676,https://www.huffingtonpost.com/entry/expanding-the-emergency-r_b_14444940.html,Expanding the Emergency Room Model: <br>'Central Care System' Could Help Americans <br>Gain Universal Health Care Access,Health,Expanding the Emergency Room Model:'Central Care System' Could Help AmericansGain Universal Health Care Access,"Dr. Sudip Bose, Contributor★Emergency Physician ★Iraq War Veteran ★CNN Hero for treating ...",2017-01-28
46508,https://www.huffingtonpost.com/entry/the-quick-search-you-shou_b_13679592.html,The Quick Search You Should Do in Your Rental Property Due Diligence,Business,The Quick Search You Should Do in Your Rental Property Due Diligence,"Dean Graziosi, ContributorNew York Times Best Selling Author",2017-01-08
46526,https://www.huffingtonpost.com/entry/stage-door-ute-lempers-so_b_14041358.html,"Stage Door: <i>Ute Lemper's Songs From The Broken Heart, Confucius</i>",Arts & Culture,"Stage Door:Ute Lemper's Songs From The Broken Heart, Confucius","Fern Siegel, ContributorDeputy Editor, MediaPost",2017-01-08
46529,https://www.huffingtonpost.com/entry/goals-2017-tax-planning_b_14039352.html,Goals 2017: Tax Planning & Timing,Business,Goals 2017: Tax Planning & Timing,"Mark Steber, ContributorChief Tax Officer, Jackson Hewitt Tax Service Inc.",2017-01-08
47075,https://www.huffingtonpost.com/entry/smoke-and-mirrors-behind-_b_13919130.html,Smoke and Mirrors: Behind the scenes of Student Filmmaking,Lifestyle,,"Desirae Hoover, ContributorWriter, Filmmaker, Activist",2017-01-02
47141,https://www.huffingtonpost.com/entry/climate-change-this-week_b_13924534.html,"Climate Change This Week: Vanishing Life, Solar Power Boom Year, and More!",Science & Environment,"Climate Change This Week: Vanishing Life, Solar Power Boom Year, and More!","Mary Ellen Harte, ContributorBiologist and author",2017-01-01
47145,https://www.huffingtonpost.com/entry/and-you-thought-your-comm_b_13922184.html,<strong>And You Thought Your Commute Was Difficult? Check Out The Odyssey!</strong>,Lifestyle,And You Thought Your Commute Was Difficult? Check Out The Odyssey!,"Sidonie Sawyer, ContributorBorn in France, immigrated to the USA / Features and Travel Wr...",2017-01-01
47484,https://www.huffingtonpost.com/entry/post_13790_b_13649258.html,<i>The Misinformation Age</i>: Exposing Fake News Does Not Absolve Mainstream Media's Own Failures,News,The Misinformation Age: Exposing Fake News Does Not Absolve Mainstream Media's Own Failures,"Dr. Milton Mankoff, ContributorSociologist and psychotherapist interested in world affairs, c...",2016-12-28
47489,https://www.huffingtonpost.com/entry/how-the-state-of-educatio_b_13745576.html,How The State Of Education Will Affect The Global Landscape: Let's Prepare the United States For A Future Ready Movement,Business,How The State Of Education Will Affect The Global Landscape: Let's Prepare the United States For A Future Ready Movement,"JD Hoye, ContributorPresident, NAF",2016-12-28
47705,https://www.huffingtonpost.com/entry/simple-giftsfor-the-holid_b_13829150.html,"Simple Gifts--for the Holidays (Holy Daze) or If We Do Not Know Your Wishes, How Can We Follow Them?",Health,"Simple Gifts--for the Holidays (Holy Daze) or If We Do Not Know Your Wishes, How Can We Follow Them?","J. Redwing Keyssar, ContributorRN, Author, Midwife to the Dying; Director Palliative Care, ...",2016-12-25
47719,https://www.huffingtonpost.com/entry/locations-a-wine-life-hac_b_13853986.html,Locations: A Wine Life Hack,Health,Locations: A Wine Life Hack,"Tara Fass, ContributorLicensed Psychotherapist in Los Angeles, California",2016-12-25
47728,https://www.huffingtonpost.com/entry/an-empty-free-library-nor_b_13851526.html,"An Empty Free Library, North Of Athens",News,,"Gregoris Kalai, ContributorBusy",2016-12-25
47765,https://www.huffingtonpost.com/entry/the-global-search-for-edu_b_13759366.html,The Global Search for Education: Top Global Teacher Bloggers - The Best Holiday Gifts for Your Students,Business,The Global Search for Education: Top Global Teacher Bloggers - The Best Holiday Gifts for Your Students,"C. M. Rubin, ContributorBlogger and author, 'The Real Alice in Wonderland'",2016-12-24
47767,https://www.huffingtonpost.com/entry/stage-door-finians-rainbo_b_13845664.html,Stage Door: <i>Finian's Rainbow</i>,Arts & Culture,Stage Door:Finian's Rainbow,"Fern Siegel, ContributorDeputy Editor, MediaPost",2016-12-24

It seems most of these are missing descriptions and just using the headline as a description. It will be best to drop those without descriptions for our model

In [41]:
#drop columns with missing descriptions from original df
data = data[data['short_description'] != '']
data.info()

<class 'pandas.DataFrame'>
Index: 189802 entries, 0 to 209526
Data columns (total 6 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   link               189802 non-null  str
 1   headline           189802 non-null  str
 2   category           189802 non-null  str
 3   short_description  189802 non-null  str
 4   authors            189802 non-null  str
 5   date               189802 non-null  datetime64[us]
dtypes: datetime64[us](1), str(5)
memory usage: 10.1 MB

## Combine headline & description

This will make it easier to have one category for NLP processes

In [42]:
#combine then drop individual columns
data['description'] = data['headline'] + ' ' + data['short_description']
data.drop(columns=['headline', 'short_description'], inplace=True)

data.head()

,link,category,authors,date,description
0,https://www.huffpost.com/entry/covid-boosters-uptake-us_n_632d719ee4b087fae6feaac9,News,"Carla K. Johnson, AP",2022-09-23,Over 4 Million Americans Roll Up Sleeves For Omicron-Targeted COVID Boosters Health experts said it is too early to predict whether demand would match up with the 171 million doses of the new boosters the U.S. ordered for the fall.
1,https://www.huffpost.com/entry/american-airlines-passenger-banned-flight-attendant-punch-justice-department_n_632e25d3e4b0e247890329fe,News,Mary Papenfuss,2022-09-23,"American Airlines Flyer Charged, Banned For Life After Punching Flight Attendant On Video He was subdued by passengers and crew when he fled to the back of the aircraft after the confrontation, according to the U.S. attorney's office in Los Angeles."
2,https://www.huffpost.com/entry/funniest-tweets-cats-dogs-september-17-23_n_632de332e4b0695c1d81dc02,Entertainment,Elyse Wanshel,2022-09-23,"23 Of The Funniest Tweets About Cats And Dogs This Week (Sept. 17-23) ""Until you have a dog you don't understand what could be eaten."""
3,https://www.huffpost.com/entry/funniest-parenting-tweets_l_632d7d15e4b0d12b5403e479,Lifestyle,Caroline Bologna,2022-09-23,"The Funniest Tweets From Parents This Week (Sept. 17-23) ""Accidentally put grown-up toothpaste on my toddler’s toothbrush and he screamed like I was cleaning his teeth with a Carolina Reaper dipped in Tabasco sauce."""
4,https://www.huffpost.com/entry/amy-cooper-loses-discrimination-lawsuit-franklin-templeton_n_632c6463e4b09d8701bd227e,News,Nina Golgowski,2022-09-22,Woman Who Called Cops On Black Bird-Watcher Loses Lawsuit Against Ex-Employer Amy Cooper accused investment firm Franklin Templeton of unfairly firing her and branding her a racist after video of the Central Park encounter went viral.

# Export Data

In [ ]:
#export cleaned df
data.to_csv('../data/processed/news_data_cleaned.csv', index=False)